1 stdcall -private DllMain(long long ptr)
2 stdcall XInputGetState(long ptr)
3 stdcall XInputSetState(long ptr)
4 stdcall XInputGetCapabilities(long long ptr)
5 stdcall XInputEnable(long)
6 stdcall XInputGetDSoundAudioDeviceGuids(long ptr ptr)
7 stdcall XInputGetBatteryInformation(long ptr ptr)
8 stdcall XInputGetKeystroke(long long ptr)
10 stdcall XInputGetAudioDeviceIds(long ptr ptr ptr ptr)
100 stdcall _XInputGetStateEx(long ptr) xinput1_3.XInputGetState
